### PR TITLE
fix crumb issue with Jenkins 2.176.2+/2.186+

### LINKED ISSUE #67: POST API calls '403 No valid crumb was included in the request'
### Expected Behavior

Use the jenkins-rest lib with user/password credentials to perform GET or POST underlying Rest API calls

### Current Behavior

All POST requests fail when running Jenkins 2.176.2+/2.186+ with error: `HTTP/1.1 403 No valid crumb was included in the request`

### Context

This issue only occurs when running Jenkins 2.176.2+/2.186+ and seems related to security settings changes: https://jenkins.io/security/advisory/2019-07-17/#SECURITY-626
This link provides workarounds to make the calls work but they
- require extra Jenkins configuration
- reduce security protection

The security advisory suggests to now pass the session id retrieved when getting the crumb to all authenticated requests.   
I currently don't know this session id is the `X-Jenkins-Session` header or the `JSESSIONID` cookie.

### Steps to Reproduce (for bugs)

Base commit: `master` branch b3e01c05 (latest 0.0.19 release is also affected)
- Start a Jenkins 2.176.2+/2.186+ local instance (I used a Jenkins Docker container)
- Jenkins configuration: activate the `CSRF Protection` and use the `Default Crumb Issuer` (see https://wiki.jenkins.io/display/JENKINS/CSRF+Protection)
- Run integration tests: `./gradlew clean build integTest `
- All http POST requests to Jenkins API receive a HTTP 403 status response

<details><summary>Debug http traces generated by integration tests</summary>
<p>

```
11:02:13.914 [Test worker] DEBUG org.jclouds.rest.internal.InvokeHttpMethod - >> invoking jobs:build
11:02:13.934 [Test worker] DEBUG org.jclouds.rest.internal.InvokeHttpMethod - >> invoking crumb-issuer:crumb
11:02:13.936 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Sending request 559347004: GET http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat%28//crumbRequestField,%22%3A%22,//crumb%29 HTTP/1.1
11:02:13.936 [Test worker] DEBUG jclouds.headers - >> GET http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat%28//crumbRequestField,%22%3A%22,//crumb%29 HTTP/1.1
11:02:13.937 [Test worker] DEBUG jclouds.headers - >> Accept: text/plain
11:02:13.937 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic YWRtaW46YWRtaW4=
11:02:14.470 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response 559347004: HTTP/1.1 200 OK
11:02:14.471 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 200 OK
11:02:14.471 [Test worker] DEBUG jclouds.headers - << X-Jenkins-Session: 0ae78274
11:02:14.471 [Test worker] DEBUG jclouds.headers - << X-Jenkins: 2.190.1
11:02:14.471 [Test worker] DEBUG jclouds.headers - << Server: Jetty(9.4.z-SNAPSHOT)
11:02:14.471 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
11:02:14.472 [Test worker] DEBUG jclouds.headers - << Set-Cookie: JSESSIONID.1af1c15a=node01gqw35ypjb5i9gnfzuer6qf60.node0;Path=/;HttpOnly
11:02:14.472 [Test worker] DEBUG jclouds.headers - << Date: Thu, 03 Oct 2019 09:02:14 GMT
11:02:14.472 [Test worker] DEBUG jclouds.headers - << Content-Type: text/plain;charset=utf-8
11:02:14.472 [Test worker] DEBUG jclouds.headers - << Content-Length: 78
11:02:14.475 [Test worker] DEBUG jclouds.headers - << Expires: Thu Jan 01 01:00:00 CET 1970
11:02:14.480 [Test worker] DEBUG jclouds.wire - << "Jenkins-Crumb:57de4a3074e2bee0231bdfab6bd63e33c9200501497fe83b3390c68dfe7edbb5"
11:02:14.484 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Sending request -134656407: POST http://127.0.0.1:8080/job/a0571fd6b9d8443ba593add116bae8a4/build HTTP/1.1
11:02:14.484 [Test worker] DEBUG jclouds.headers - >> POST http://127.0.0.1:8080/job/a0571fd6b9d8443ba593add116bae8a4/build HTTP/1.1
11:02:14.485 [Test worker] DEBUG jclouds.headers - >> Accept: application/unknown
11:02:14.485 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic YWRtaW46YWRtaW4=
11:02:14.485 [Test worker] DEBUG jclouds.headers - >> Jenkins-Crumb: 57de4a3074e2bee0231bdfab6bd63e33c9200501497fe83b3390c68dfe7edbb5
11:02:14.502 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response -134656407: HTTP/1.1 403 No valid crumb was included in the request
11:02:14.502 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 403 No valid crumb was included in the request
11:02:14.502 [Test worker] DEBUG jclouds.headers - << Server: Jetty(9.4.z-SNAPSHOT)
11:02:14.502 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
11:02:14.502 [Test worker] DEBUG jclouds.headers - << Set-Cookie: JSESSIONID.1af1c15a=node01ilzetxztr6rbbhspkddjs2fw1.node0;Path=/;HttpOnly
11:02:14.502 [Test worker] DEBUG jclouds.headers - << Date: Thu, 03 Oct 2019 09:02:14 GMT
```

</p>
</details>

### Your Environment

JVM:          1.8.0_212 ( 25.212-b04)
OS:           Windows 10 10.0 amd64

### PR DESCRIPTION
**Pull request by tbouffard**
Always pass the JSESSIONID in addition to the crumb
See https://jenkins.io/security/advisory/2019-07-17/#SECURITY-626

closes #67

**Implementation note**
I am not used to playing with AutoValue and jclouds, so don't hesitate to spot any bad practices on these areas 😸

### CODE REVIEW

File: src/main/java/com/cdancy/jenkins/rest/domain/crumb/Crumb.java [hunk 1]
```diff
@@ -24,18 +24,34 @@
...
+    public static Crumb create(final String value,
+            final List<Error> errors) {
+
+        return create(value, null, errors);
+    }
+
+    @SerializedNames({ "value", "sessionIdCookie" })
+    public static Crumb create(final String value, final String sessionIdCookie) {
+        return create(value, sessionIdCookie, null);
+    }
```
Comment (cdancy) [inline src/main/java/com/cdancy/jenkins/rest/domain/crumb/Crumb.java]: With these changes I _believe_ this `create` method would no longer be used if I'm not mistaken. If that's so feel free to rip it out and put the `@SerializedNames` anno on the new method.

File: src/main/java/com/cdancy/jenkins/rest/parsers/CrumbParser.java [hunk 2]
```diff
@@ -38,13 +39,24 @@ public Crumb apply(final HttpResponse input) {
...
     }
+
+    private static String crumbValue(HttpResponse input) throws IOException {
+        return Strings2.toStringAndClose(input.getPayload().openStream())
+                .split(":")[1];
+    }
+
+    private static String sessionIdCookie(HttpResponse input) {
+        return input.getHeaders().get(HttpHeaders.SET_COOKIE).stream()
+            .filter(c -> c.startsWith("JSESSIONID"))
```
Comment (cdancy) [inline src/main/java/com/cdancy/jenkins/rest/parsers/CrumbParser.java]: Can we turn JSESSIONID into a `static final String` constant and put it somewhere that makes the most sense? Believe there is a static-variables class around here somewhere

**Comment by tbouffard** [comment]
Thanks @cdancy for the quick feedbacks, I will manage them soon
I have done some extra testing and the current implementation seems not work anymore after my 2 last commits. I am going to review them and come back to you when the integration tests pass

**Comment by cdancy** [comment]
@tbouffard sounds good and thanks! Let me know if you need any help one way or another.

File: src/main/java/com/cdancy/jenkins/rest/parsers/CrumbParser.java (hunk 2 above)
Comment (tbouffard) [reply src/main/java/com/cdancy/jenkins/rest/parsers/CrumbParser.java]: I found the [com.cdancy.jenkins.rest.JenkinsConstants](https://github.com/cdancy/jenkins-rest/blob/v0.0.20/src/main/java/com/cdancy/jenkins/rest/JenkinsConstants.java#L23) class. Is that the one you had in mind?

Comment (cdancy) [reply src/main/java/com/cdancy/jenkins/rest/parsers/CrumbParser.java]: Yeah exactly

File: src/main/java/com/cdancy/jenkins/rest/domain/crumb/Crumb.java (hunk 1 above)
Comment (tbouffard) [reply src/main/java/com/cdancy/jenkins/rest/domain/crumb/Crumb.java]: Sorry, I don't understand which `create` method you have in mind. The new private one with 3 arguments?
I don't know what is the purpose of the `SerializedNames` annotation, I guessed it has to be put on public methods, I just mimic the previously existing public method. But I can remove the anno from the 2 public methods and put it only on the private one.
Do you think running integration tests is enough to ensure this change make all things work?

Comment (cdancy) [reply src/main/java/com/cdancy/jenkins/rest/domain/crumb/Crumb.java]: It was only a possible suggestion. If your IDE says it's no longer being used you can yank it out otherwise just leave it. No worries one way or another.

Comment (tbouffard) [reply src/main/java/com/cdancy/jenkins/rest/domain/crumb/Crumb.java]: ok
All public methods of this class are used

**Comment by cdancy** [comment]
@tbouffard have you tested the impl yet? Are you happy with things? Any gotchas one way or another?

**Comment by tbouffard** [comment]
I didn't have much time to work on this PR except to ensure that I have a correct Jenkins instance for integration tests (see #72).
I still have a failling integration tests (and dependent tests are then skipped) when running Jenkins 2.176.1 with the new implementation
I currently can't provide the error here but I will share it on the begining of next week

File: src/main/java/com/cdancy/jenkins/rest/parsers/CrumbParser.java (hunk 2 above)
Comment (tbouffard) [reply src/main/java/com/cdancy/jenkins/rest/parsers/CrumbParser.java]: done, see d0a16f2

**Comment by tbouffard** [comment]
I have some time today to work on this. The issue I mentionned in https://github.com/cdancy/jenkins-rest/pull/70#issuecomment-548481356 was the one seen on #75 
Here my tests results as of today

On Jenkins 2.164.3 without fix (master commit 401f4f3f)
no CSRF: a single test is failing when retrieving the Crumb. This is the normal behaviour as in this case, no Crumb is available

```java
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.assertNotNull(Assert.java:422)
	at org.testng.Assert.assertNotNull(Assert.java:407)
	at com.cdancy.jenkins.rest.features.CrumbIssuerApiLiveTest.testGetCrumb(CrumbIssuerApiLiveTest.java:34)
```
```  
16:43:47.721 [Test worker] DEBUG org.jclouds.rest.internal.InvokeHttpMethod - >> invoking crumb-issuer:crumb
16:43:47.726 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Sending request 559347004: GET http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat%28//crumbRequestField,%22%3A%22,//crumb%29 HTTP/1.1
16:43:47.726 [Test worker] DEBUG jclouds.headers - >> GET http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat%28//crumbRequestField,%22%3A%22,//crumb%29 HTTP/1.1
16:43:47.727 [Test worker] DEBUG jclouds.headers - >> Accept: text/plain
16:43:47.727 [Test worker] DEBUG jclouds.headers - >> Authorization: Basic YWRtaW46YWRtaW4=
16:43:47.820 [Test worker] DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService - Receiving response 559347004: HTTP/1.1 404 Not Found
16:43:47.820 [Test worker] DEBUG jclouds.headers - << HTTP/1.1 404 Not Found
16:43:47.820 [Test worker] DEBUG jclouds.headers - << Server: Jetty(9.4.z-SNAPSHOT)
16:43:47.821 [Test worker] DEBUG jclouds.headers - << X-Content-Type-Options: nosniff
16:43:47.821 [Test worker] DEBUG jclouds.headers - << Date: Thu, 12 Dec 2019 15:43:47 GMT
```

2.164.3 with the fix (commit d0a16f2)
- with CSRF: OK
- without CSRF: OK (same Crumb test failing as without the fix)

2.190.3 with the fix (commit d0a16f2)
- with CSRF: sessionId is not passed. This is strange I remember this worked with 2.176.3. New tests required
- without CSRF: OK (same Crumb test failing as without the fix)

**Comment by cdancy** [comment]
@tbouffard let me know if you need any help here. Would be great to have this in and "just work" across the board.

**Comment by tbouffard** [comment]
@cdancy I have finally figure out the cause of the failure with Jenkins 2.176.2+, see 
5d70101, so this should be ok now on Jenkins 2.190.3 with CSRF protection enabled

Can you run the tests on your side to ensure I didn't miss anything with my own testing.
I can also rebase the PR on the latest master commit to make Travis run integration tests and then update the Jenkins version to the latest available LTS.

**Comment by cdancy** [comment]
@tbouffard yes please rebase off of master and I'll run things as here as well.

**Comment by tbouffard** [comment]
Rebase done. If Travis tests pass, I will bump the jenkins version used in the Docker container  to the latest one (2.190.3)

**Comment by cdancy** [comment]
@tbouffard thanks for the fix/enhancement!

**Comment by cdancy** [comment]
@tbouffard release `v0.0.22` has been released with this change.

**Comment by tbouffard** [comment]
@cdancy Great and thanks for the support. Very helpful to make this contribution complete. I hope to be quicker next time 😄

**Comment by cdancy** [comment]
@tbouffard no worries. We all have lives and day-jobs to attend to. Just happy for the contribution either way.
