### PR TITLE
Fix #62

### LINKED ISSUE #62: JenkinsFallbacks#getErrors NPEs on message from ForbiddenException
When my bearer auth failed, a ForbiddenException was thrown with the message: 
```
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fjob%2Fmicroservices-build%2Fbuild'/><script>window.location.replace('/login?from=%2Fjob%2Fmicroservices-build%2Fbuild');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:
  
Permission you need to have (but didn't): hudson.model.Item.Build
 ... which is implied by: hudson.security.Permission.GenericUpdate
 ... which is implied by: hudson.security.Permission.GenericWrite
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>
```

JenkinsFallbacks attempts to parse this message at https://github.com/cdancy/jenkins-rest/blob/b171a7ceac9341fddd41af2121280c99d2c883ae/src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java#L155-L163
The `message` var ends up being null and is not marked as `@Nullable` on `Error`, so AutoValue throws an NPE.

### Expected Behavior
No NPE.

### Current Behavior
NPE.

### Context
This is happening when my auth is rejected on an API action that requires auth (building a Job).

### Steps to Reproduce (for bugs)
I don't have a reproducing project to share.  Let me know if one is needed.

### Your Environment
Jenkins 2.150.1 (November 2018)

### PR DESCRIPTION
**Pull request by isker**
The commit messages explain everything.  

I could not find test coverage of this method.  If you'd like test coverage please advise how to do that.

Closes #62

### CODE REVIEW

**Comment by isker** [comment]
FWIW all of those tests fail on my machine on master too.

File: src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java [hunk 1]
```diff
@@ -153,7 +153,7 @@ public static SystemInfo createSystemInfoFromErrors(final List<Error> errors) {
         final List<Error> errors = Lists.newArrayList();
 
         String context = null;
-        String message = null;
+        String message = output.getMessage();
```
Comment (cdancy) [inline src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java]: We shouldn't need to do this now that we have the @Nullable annotation.

File: gradle/wrapper/gradle-wrapper.properties [hunk 2]
```diff
@@ -3,4 +3,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.3-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```
Comment (cdancy) [inline gradle/wrapper/gradle-wrapper.properties]: Lets back out this change and the one above as I haven't yet tested if the release pipeline, with all the older gradle plugins, will even work with this change.

File: src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java (hunk 1 above)
Comment (isker) [reply src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java]: This will provide some support for exceptions whose messages do not parse with "->" below.

File: gradle/wrapper/gradle-wrapper.properties (hunk 2 above)
Comment (isker) [reply gradle/wrapper/gradle-wrapper.properties]: Okay.

File: src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java (hunk 1 above)
Comment (cdancy) [reply src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java]: Fair enough.

**Comment by cdancy** [comment]
Thanks for the fix @isker ! Doing a point release now. And apologies for the delay as I've been busy with other things.

**Comment by cdancy** [comment]
`v0.0.19` has been released with fix.
